GET http://localhost:5000/products

###

GET http://localhost:5000/products/2

###

POST http://localhost:5000/products 
Content-Type: application/json

{
    "name": "CPpppppUUU",
    "description": "1tb cpssudfafafa desk",
    "quantity": "11"
}

###

DELETE http://localhost:5000/products/1